### ISSUE TITLE
[TODO]: Migrate from Javascript to TypeScript

### ISSUE THREAD

**Issue by DJBlackEagle** [DJBlackEagle/shared-project-tools#253]
### Is there an existing issue that is already proposing this?

- [X] I use the right issue type

### Describe your todo.

ToDo's for issue: #249 

- [x] Add TypeScript, ts-node as package
- [x] Configure tsconfig..json
- [x] Migrate configs to TypeScript
- [x] Use sharedConfig export variable
- [x] Update README.md
- [x] Copy Project ESLint config, to the local ESLint config
- [x] Copy Project Prettier config, to the local Prettier config
