### ISSUE TITLE
[TODO] Add Tag on issue creating

### ISSUE THREAD

**Issue by DJBlackEagle** [DJBlackEagle/shared-project-tools#323]
### Is there an existing issue that is already proposing this?

- [X] I use the right issue type

### Describe your todo.

Add Tags to all issues (create):

- [x] Bug Report: [BUG]
- [x] Feature Request: [FEAT]
- [x] Suggestion for Improving Performance: [PERF]
- [x] Regression: [REGRESSION]
- [x] Todo: [TODO]
- [x] Repository: [REPO]
